## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

In [1]:
#import numpy
import numpy as np

#make two vectors
x=np.arange(5,10)
y=np.arange(15,20)
z=np.arange(0,10,2) #np.arange(start, stop, step)
m=np.linspace(1,10,10)
print(x)
print(y)
print(z)


[5 6 7 8 9]
[15 16 17 18 19]
[0 2 4 6 8]


In [2]:
#A.Compute the outer product of those vectors

t_out=[] #initialize an empty list

assert (len(x)==len(y)) #make sure the length is the same

for i in range(len(x)):
    row=[]
    for j in range(len(y)):
        row.append(x[i]*y[j])
    t_out.append(row)
print("outer product:")
t_out

outer product:


[[75, 80, 85, 90, 95],
 [90, 96, 102, 108, 114],
 [105, 112, 119, 126, 133],
 [120, 128, 136, 144, 152],
 [135, 144, 153, 162, 171]]

In [3]:
t1_out=np.outer(x,y)
print("outer product:")
t1_out


outer product:


array([[ 75,  80,  85,  90,  95],
       [ 90,  96, 102, 108, 114],
       [105, 112, 119, 126, 133],
       [120, 128, 136, 144, 152],
       [135, 144, 153, 162, 171]])

In [4]:
#A.Compute the outer product of those vectors

assert(len(x)==len(y))

p_out=[[x[i]*y[j] for i in range(len(x))] for j in range(len(y))]
print("outer product:")
p_out

outer product:


[[75, 90, 105, 120, 135],
 [80, 96, 112, 128, 144],
 [85, 102, 119, 136, 153],
 [90, 108, 126, 144, 162],
 [95, 114, 133, 152, 171]]

In [5]:
#Compute the "trace" of the resulting matrix
T=[]
for i in range(len(t1_out)):
    T.append(t1_out[i][i])
a=np.sum(T)
print(a)

605


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [6]:
#import numpy
import numpy as np

#make two matrics
A=np.random.rand(4,3)
B=np.random.rand(3,4)
print(A)
print(B)
print(A[0,0])

[[0.13015705 0.97144612 0.17030483]
 [0.48289356 0.36352484 0.13767199]
 [0.76879501 0.72417403 0.1902008 ]
 [0.01196766 0.88856225 0.70311429]]
[[0.89425914 0.2020949  0.6484442  0.7727864 ]
 [0.71210077 0.87587159 0.59972341 0.81107513]
 [0.49762081 0.90179311 0.33292895 0.81047196]]
0.1301570460297623


In [7]:
#A conventional for-loop
C=[] #set an empty
assert np.shape(A)[1]==np.shape(B)[0]

for i in range(np.shape(A)[0]):
    row1=[]
    for j in range(np.shape(B)[1]):
        #row2=[]
        kk=0
        for m in range(np.shape(A)[1]):
            kk=kk+A[i,m]*B[m,j]
        row1.append(kk)
    C.append(row1)
print('Matrix Multiplication:')
C

Matrix Multiplication:


[[0.8929088874616908,
  1.0307458646522123,
  0.7236979697665487,
  1.0265266830078237],
 [0.7592067377944683,
  0.5401430541654332,
  0.5769788682271249,
  0.7795988157234732],
 [1.2978347249287685,
  0.9611747820221783,
  0.9961481340821767,
  1.3356262927973894],
 [0.9933323496248033,
  1.4147486629346069,
  0.7747390392051818,
  1.299793606581655]]

In [8]:
#A conventional for-loop
C=[] #set an empty
assert np.shape(A)[1]==np.shape(B)[0]

for i in range(np.shape(A)[0]):
    row1=[]
    for j in range(np.shape(B)[1]):
        row2=[]
        for m in range(np.shape(A)[1]):
            row2.append(A[i,m]*B[m,j])
        row1.append(np.sum(row2))
    C.append(row1)
print('Matrix Multiplication:')
C

Matrix Multiplication:


[[0.8929088874616908,
  1.0307458646522123,
  0.7236979697665487,
  1.0265266830078237],
 [0.7592067377944683,
  0.5401430541654332,
  0.5769788682271249,
  0.7795988157234732],
 [1.2978347249287685,
  0.9611747820221783,
  0.9961481340821767,
  1.3356262927973894],
 [0.9933323496248033,
  1.4147486629346069,
  0.7747390392051818,
  1.299793606581655]]

In [9]:
C1=np.matmul(A,B)
C1

array([[0.89290889, 1.03074586, 0.72369797, 1.02652668],
       [0.75920674, 0.54014305, 0.57697887, 0.77959882],
       [1.29783472, 0.96117478, 0.99614813, 1.33562629],
       [0.99333235, 1.41474866, 0.77473904, 1.29979361]])